<?php 
return array (
  'URL_PATHINFO_FETCH' => 'ORIG_PATH_INFO,REDIRECT_PATH_INFO,REDIRECT_URL',
  'URL_ROUTER_ON' => true,
  'URL_MODEL' =>2,
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'gps',
  'DB_USER' => 'root',
  'DB_PWD' => 'mysqlpwd',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'gps_',
  'DB_CHARSET' => 'utf8',
  'DB_DEBUG' => true,
  'TITLE' => '广域差分实时产品精度评估监控平台',
  'KEYWORDS' => '数据流质量监控',
  'DESCRIPTION' => '网站主要实现广域差分服务实时产品精度监测与评估软件的数据在网站上实时动态显示，为其服务应用提供全面的技术保障。',
  'EMAIL' => 'sww@whedu.com',
  'CONTACT' => '武汉大学',
  'PHONE' => '+86 27-68778971 / 68778240',
  'FAX' => '+86 27-68778971 / 68778240',
  'ICP' => '苏ICP-12345678',
  'COPY' => '武汉大学导航定位中心，版权所有。',
  'ADDRESS' => '武汉市武汉大学信息学部',
)?>